/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.daniel.viziontask.ui;

/**
 *
 * @author Daniel Estevão
 */
// Adicione estes imports no início do arquivo
// Adicione estes imports no início do arquivo
import com.daniel.viziontask.model.Task;
import com.daniel.viziontask.repository.TaskRepository;
import com.daniel.viziontask.service.TaskService;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TaskManagerUI extends javax.swing.JPanel {

    private TaskService taskService;
    private String selectedTaskId;
    private DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form TaskManagerUI
     */
    public TaskManagerUI() {
        initComponents();

        // Inicializa o serviço de tarefas
        TaskRepository taskRepository = new TaskRepository();
        this.taskService = new TaskService(taskRepository);

        // Configura o combo box de prioridade
        selectprioridade.removeAllItems();
        for (Task.Priority priority : Task.Priority.values()) {
            selectprioridade.addItem(priority.toString());
        }

        // Configura a tabela
        configureTable();

        // Carrega as tarefas existentes
        loadTasks();
    }

    private void configureTable() {
        DefaultTableModel model = (DefaultTableModel) tabelaFormulario.getModel();
        model.setColumnIdentifiers(new String[]{"ID", "Título", "Prioridade", "Data Limite", "Status"});

        // Adiciona listener para selecionar tarefas
        tabelaFormulario.getSelectionModel().addListSelectionListener(e -> {
            int selectedRow = tabelaFormulario.getSelectedRow();
            if (selectedRow >= 0) {
                selectedTaskId = (String) tabelaFormulario.getValueAt(selectedRow, 0);
                Task task = taskService.findTaskById(selectedTaskId);
                if (task != null) {
                    inputtitulo.setText(task.getTitle());
                    textareadescricao.setText(task.getDescription());
                    if (task.getDueDate() != null) {
                        inputdatalimite.setText(task.getDueDate().format(dateFormatter));
                    }
                    selectprioridade.setSelectedItem(task.getPriority().toString());
                }
            }
        });
    }

    private void loadTasks() {
        DefaultTableModel model = (DefaultTableModel) tabelaFormulario.getModel();
        model.setRowCount(0);

        for (Task task : taskService.findAllTasks()) {
            model.addRow(new Object[]{
                task.getId(),
                task.getTitle(),
                task.getPriority(),
                task.getDueDate() != null ? task.getDueDate().format(dateFormatter) : "",
                task.isCompleted() ? "Concluída" : "Pendente"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpainel = new javax.swing.JScrollPane();
        formularioPainel = new javax.swing.JPanel();
        tituloLogo = new javax.swing.JLabel();
        lineSeparacao = new javax.swing.JSeparator();
        inputtitulo = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        datalimite = new javax.swing.JLabel();
        prioridade = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareadescricao = new javax.swing.JTextArea();
        inputdatalimite = new javax.swing.JFormattedTextField();
        selectprioridade = new javax.swing.JComboBox<>();
        addbutton = new javax.swing.JButton();
        editebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        conclusionbutton = new javax.swing.JButton();
        tabela = new javax.swing.JLabel();
        scrolltable = new javax.swing.JScrollPane();
        tabelaFormulario = new javax.swing.JTable();
        lineSeparacao1 = new javax.swing.JSeparator();

        formularioPainel.setBackground(new java.awt.Color(204, 204, 204));

        tituloLogo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloLogo.setText("VizioonTask");

        lineSeparacao.setForeground(new java.awt.Color(51, 51, 51));

        inputtitulo.setToolTipText("");

        titulo.setText("Título");

        descricao.setText("Descrição");

        datalimite.setText("Data Limite");

        prioridade.setText("Prioridade");

        textareadescricao.setColumns(20);
        textareadescricao.setRows(5);
        jScrollPane2.setViewportView(textareadescricao);

        try {
            inputdatalimite.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        selectprioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectprioridadeActionPerformed(evt);
            }
        });

        addbutton.setText("adicionar");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        editebutton.setText("editar");
        editebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editebuttonActionPerformed(evt);
            }
        });

        deletebutton.setText("deletar");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        conclusionbutton.setText("concluir");
        conclusionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusionbuttonActionPerformed(evt);
            }
        });

        tabela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabela.setText("Tabela");

        tabelaFormulario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Descricao", "Data Limite", "Prioridade"
            }
        ));
        scrolltable.setViewportView(tabelaFormulario);

        lineSeparacao1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout formularioPainelLayout = new javax.swing.GroupLayout(formularioPainel);
        formularioPainel.setLayout(formularioPainelLayout);
        formularioPainelLayout.setHorizontalGroup(
            formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioPainelLayout.createSequentialGroup()
                        .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(formularioPainelLayout.createSequentialGroup()
                                .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloLogo)
                                    .addComponent(inputtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(formularioPainelLayout.createSequentialGroup()
                                        .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descricao)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputdatalimite)
                                            .addComponent(datalimite)
                                            .addComponent(prioridade)
                                            .addComponent(selectprioridade, 0, 154, Short.MAX_VALUE))))
                                .addGap(0, 190, Short.MAX_VALUE)))
                        .addContainerGap(195, Short.MAX_VALUE))
                    .addGroup(formularioPainelLayout.createSequentialGroup()
                        .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioPainelLayout.createSequentialGroup()
                                .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conclusionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lineSeparacao, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formularioPainelLayout.createSequentialGroup()
                        .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tabela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lineSeparacao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(scrolltable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        formularioPainelLayout.setVerticalGroup(
            formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparacao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricao)
                    .addComponent(datalimite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formularioPainelLayout.createSequentialGroup()
                        .addComponent(inputdatalimite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prioridade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectprioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(formularioPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(editebutton)
                    .addComponent(deletebutton)
                    .addComponent(conclusionbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSeparacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolltable, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        scrollpainel.setViewportView(formularioPainel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpainel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpainel, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectprioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectprioridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectprioridadeActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        String title = inputtitulo.getText().trim();
        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O título é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String description = textareadescricao.getText().trim();

        // Converte a prioridade selecionada
        Task.Priority priority = Task.Priority.valueOf(selectprioridade.getSelectedItem().toString());

        // Converte a data de string para LocalDate
        LocalDate dueDate = null;
        try {
            String dateStr = inputdatalimite.getText().trim();
            if (!dateStr.isEmpty() && !dateStr.equals("  /  /    ")) {
                dueDate = LocalDate.parse(dateStr, dateFormatter);
            }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use DD/MM/AAAA", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        taskService.createTask(title, description, dueDate, priority);
        clearFields();
        loadTasks();
    }//GEN-LAST:event_addbuttonActionPerformed

    private void editebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editebuttonActionPerformed
        if (selectedTaskId == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma tarefa para editar", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Task task = taskService.findTaskById(selectedTaskId);
        if (task != null) {
            String title = inputtitulo.getText().trim();
            if (title.isEmpty()) {
                JOptionPane.showMessageDialog(this, "O título é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Converte a data de string para LocalDate
            LocalDate dueDate = null;
            try {
                String dateStr = inputdatalimite.getText().trim();
                if (!dateStr.isEmpty() && !dateStr.equals("  /  /    ")) {
                    dueDate = LocalDate.parse(dateStr, dateFormatter);
                }
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Formato de data inválido. Use DD/MM/AAAA", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            task.setTitle(title);
            task.setDescription(textareadescricao.getText().trim());
            task.setPriority(Task.Priority.valueOf(selectprioridade.getSelectedItem().toString()));
            task.setDueDate(dueDate);

            taskService.updateTask(task);
            selectedTaskId = null;
            clearFields();
            loadTasks();
        }
    }//GEN-LAST:event_editebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        if (selectedTaskId == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma tarefa para excluir", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir esta tarefa?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            taskService.deleteTask(selectedTaskId);
            selectedTaskId = null;
            clearFields();
            loadTasks();
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void conclusionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusionbuttonActionPerformed
        if (selectedTaskId == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma tarefa para alterar o status", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Task task = taskService.findTaskById(selectedTaskId);
        if (task != null) {
            if (task.isCompleted()) {
                taskService.markTaskAsIncomplete(selectedTaskId);
            } else {
                taskService.markTaskAsCompleted(selectedTaskId);
            }
            selectedTaskId = null;
            clearFields();
            loadTasks();
        }
    }//GEN-LAST:event_conclusionbuttonActionPerformed

    private void clearFields() {
        inputtitulo.setText("");
        textareadescricao.setText("");
        inputdatalimite.setText("");
        selectprioridade.setSelectedIndex(0);
        selectedTaskId = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton conclusionbutton;
    private javax.swing.JLabel datalimite;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel descricao;
    private javax.swing.JButton editebutton;
    private javax.swing.JPanel formularioPainel;
    private javax.swing.JFormattedTextField inputdatalimite;
    private javax.swing.JTextField inputtitulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator lineSeparacao;
    private javax.swing.JSeparator lineSeparacao1;
    private javax.swing.JLabel prioridade;
    private javax.swing.JScrollPane scrollpainel;
    private javax.swing.JScrollPane scrolltable;
    private javax.swing.JComboBox<String> selectprioridade;
    private javax.swing.JLabel tabela;
    private javax.swing.JTable tabelaFormulario;
    private javax.swing.JTextArea textareadescricao;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloLogo;
    // End of variables declaration//GEN-END:variables
}
